routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\FacultyController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UniversityController;

Route::get('/', function () {
    return view('pages.auth.auth-login');
});

//Route feature contact
Route::get('/features-contact', [ContactController::class, 'show'])->name('contact');


//Route feature activities
Route::get('/features-activities', [ProfileController::class, 'activities'])->name('activities');

//Route feature tickets
Route::get('/features-tickets', [ProfileController::class, 'tickets'])->name('tickets');

//Route feature settings
Route::get('/features-settings', [SettingController::class, 'settings'])->name('settings');

//Route feature settings detail
Route::get('/features-settings-detail', [SettingController::class, 'settingDetail'])->name('setting-detail');

//Route feature post
Route::get('/features-post', [PostController::class, 'show'])->name('show');

//Route feature post
Route::get('/features-post/create', [PostController::class, 'create'])->name('create');

//Route feature post
Route::post('/features-post/store', [PostController::class, 'store'])->name('store');

Route::group(['middleware' => 'admin'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'show'])->name('home');

    Route::get('/departments', [DepartmentController::class, 'index'])->name('departments.index');

    //Route feature profile
    Route::get('/features-profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile/delete', [ProfileController::class, 'destroy'])->name('profile.delete');

    Route::post('/profile/change-password', [PasswordController::class, 'changePassword'])->name('profile.change-password');

    Route::resource('users', UserController::class);
    Route::resource('faculties', FacultyController::class);
    Route::resource('universites', UniversityController::class);
    Route::resource('attendances', AttendanceController::class);
    Route::resource('permissions', PermissionController::class);
});

app/Models/Faculty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'dean',
    ];

    // satu fakultas memiliki banyak departemen(program studi)
    public function departments()
    {
        return $this->hasMany(Department::class);
    }

    // satu fakultas memiliki banyak user
    public function user()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/FacultyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Faculty;
use Illuminate\Http\Request;

class FacultyController extends Controller
{
    //index
    public function index(Request $request)
    {
        $faculties = Faculty::when($request->input('name'), function ($query, $name) {
                $query->where('name', 'like', '%' . $name . '%');
            })
            ->orderBy('id', 'asc')
            ->paginate(10)
            ->withQueryString();

        return view('pages.faculty.index', compact('faculties'));
    }

    //edit
    public function edit($id)
    {
        $faculty = Faculty::findOrFail($id);
        return view('pages.faculty.edit', compact('faculty'));
    }

    //update faculty
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => 'required',
            'dean' => 'required|string|max:255',
        ]);

        $faculty = Faculty::findOrFail($id);
        $faculty->description = $request->description;
        $faculty->dean = $request->dean;
        $image = $request->file('logo');
        $imageName = $image->hashName();
        $image->storeAs('public/faculties', $imageName);
        $faculty->img_logo = $imageName;
        $faculty->save();
        return redirect()->route('faculties.index')->with('status', 'Faculty updated successfully');
    }

    //deleted
    public function destroy($id)
    {
        $faculty = Faculty::findOrFail($id);
        $faculty->delete();
        return redirect()->route('faculties.index')->with('status', 'Faculty deleted successfully');
    }
}

resources/views/pages/faculty/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Profil Perusahaan')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('library/bootstrap-social/assets/css/bootstrap.css') }}">

    <style>
        .logo-upload {
            position: relative;
            max-width: 205px;
        }

        .logo-upload .logo-preview {
            width: 67%;
            height: 140px;
            position: relative;
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            margin-top: 10px;
        }
    </style>
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Edit Profil Perusahaan</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item">Edit Profil Perusahaan</div>
                </div>
            </div>
            <div class="section-body">
                <h2 class="section-title">Edit Faculty</h2>
                <p class="section-lead">
                    Perbarui informasi tentang fakultas Anda di halaman ini.
                </p>

                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif

                <div class="row mt-sm-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <form method="POST" action="{{ route('faculties.update', $faculty->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Nama Fakultas</label>
                                            <input type="text" name="name" class="form-control" value="{{ $faculty->name }}" disabled>
                                            <input type="hidden" name="name" value="{{ $faculty->name }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Alamat Fakultas</label>
                                            <input type="text" name="address" class="form-control" value="{{ $faculty->address }}" disabled>
                                            <input type="hidden" name="address" value="{{ $faculty->address }}">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Deskripsi Fakultas</label>
                                            <input type="text" name="description" class="form-control" value="{{ $faculty->description }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Dekan Fakultas</label>
                                            <input type="text" name="dean" class="form-control" value="{{ $faculty->dean }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Logo</label>
                                            <div class="logo-upload">
                                                <input type="file" class="form-control" name="logo" accept=".png, .jpg, .jpeg" onchange="previewLogo(this)">
                                                <div class="logo-preview" id="logoPreview" ></div>
                                            </div>
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Total Departments</label>
                                            <input type="number" name="departments_count" class="form-control" value="{{ $faculty->departments->count() }}" disabled>
                                            <input type="hidden" name="departments_count" value="{{ $faculty->departments->count() }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraries -->
    <script src="{{ asset('library/summernote/dist/summernote-bs4.js') }}"></script>

    <!-- Page Specific JS File -->
    <script type="text/javascript">
        function previewLogo(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('logoPreview').style.backgroundImage = 'url(' + e.target.result + ')';
                    document.getElementById('logoPreview').style.display = 'none';
                    document.getElementById('logoPreview').style.display = 'block';
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endpush

resources/views/pages/faculty/index.blade.php
@extends('layouts.app')

@section('title', 'Faculties')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Faculty</h1>
                {{-- <div class="section-header-button">
                    <a href="{{ route('permissions.create') }}" class="btn btn-primary">Add New</a>
                </div> --}}
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Faculty</a></div>
                    <div class="breadcrumb-item">All Faculty</div>
                </div>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        @include('layouts.alert')
                    </div>
                </div>
                <h2 class="section-title">Faculty</h2>
                <p class="section-lead">
                    You can manage all Faculty, such as editing, deleting and more.
                </p>


                <div class="row mt-4">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>All Faculty</h4>
                            </div>
                            <div class="card-body">

                                <div class="float-right">
                                    <form method="GET" action="{{ route('faculties.index') }}">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Search by name" name="name">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="clearfix mb-3"></div>

                                <div class="table-responsive">
                                    <table class="table-striped table">
                                        <tr>
                                            <th>Name</th>
                                            <th>Address</th>
                                            <th>Description</th>
                                            <th>Dean</th>
                                            <th>Total Departments</th>
                                            <th>Logo</th>
                                            <th>Action</th>
                                        </tr>
                                        @foreach ($faculties as $faculty)
                                            <tr>

                                                <td>{{ $faculty->name }}
                                                </td>
                                                <td>
                                                    {{ $faculty->address }}
                                                </td>
                                                <td>
                                                    {{ $faculty->description }}
                                                </td>
                                                <td>
                                                    {{ $faculty->dean }}
                                                </td>
                                                <td>
                                                    {{ $faculty->departments->count() }}
                                                </td>
                                                <td>
                                                    <img src="{{ asset('storage/faculties/' . $faculty->img_logo) }}" alt="logo" style="width: 50px; height: 50px" />
                                                </td>
                                                <td>
                                                    <div class="d-flex justify-content-center">
                                                        <a href='{{ route('faculties.edit', $faculty->id) }}'
                                                            class="btn btn-sm btn-info btn-icon" title="Edit">
                                                            <i class="fas fa-edit"></i>
                                                        </a>

                                                        <form action="#"
                                                            method="POST" class="ml-2">
                                                            <input type="hidden" name="_method" value="DELETE" />
                                                            <input type="hidden" name="_token"
                                                                value="{{ csrf_token() }}" />
                                                            <button class="btn btn-sm btn-danger btn-icon confirm-delete" title="Delete">
                                                                <i class="fas fa-trash"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach


                                    </table>
                                </div>
                                <div class="float-right">
                                    {{ $faculties->withQueryString()->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/selectric/public/jquery.selectric.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/features-posts.js') }}"></script>
@endpush