routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\FacultyController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UniversityController;

Route::get('/', function () {
    return view('pages.auth.auth-login');
});

//Route feature contact
Route::get('/features-contact', [ContactController::class, 'show'])->name('contact');


//Route feature activities
Route::get('/features-activities', [ProfileController::class, 'activities'])->name('activities');

//Route feature tickets
Route::get('/features-tickets', [ProfileController::class, 'tickets'])->name('tickets');

//Route feature settings
Route::get('/features-settings', [SettingController::class, 'settings'])->name('settings');

//Route feature settings detail
Route::get('/features-settings-detail', [SettingController::class, 'settingDetail'])->name('setting-detail');

//Route feature post
Route::get('/features-post', [PostController::class, 'show'])->name('show');

//Route feature post
Route::get('/features-post/create', [PostController::class, 'create'])->name('create');

//Route feature post
Route::post('/features-post/store', [PostController::class, 'store'])->name('store');

Route::group(['middleware' => 'admin'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'show'])->name('home');

    Route::get('/departments', [DepartmentController::class, 'index'])->name('departments.index');

    //Route feature profile
    Route::get('/features-profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile/delete', [ProfileController::class, 'destroy'])->name('profile.delete');

    Route::post('/profile/change-password', [PasswordController::class, 'changePassword'])->name('profile.change-password');

    Route::resource('users', UserController::class);
    Route::resource('faculties', FacultyController::class);
    Route::resource('universites', UniversityController::class);
    Route::resource('attendances', AttendanceController::class);
    Route::resource('permissions', PermissionController::class);
});

app/Models/Permission.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'date_permission',
        'reason',
        'image',
        'status',
    ];

    public function getDatePermissionAttribute($value)
    {
        return Carbon::parse($value)->translatedFormat('d F Y');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/PermissionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{
    //create
    public function store(Request $request)
    {
        $request->validate([
            'date' => 'required|date',
            'reason' => 'required|string',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $permission = new Permission();
        $permission->user_id = $request->user()->id;
        $permission->date_permission = $request->date;
        $permission->reason = $request->reason;
        $permission->status = 'pending';

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $imageName = $image->hashName();
            $image->storeAs('public/permissions', $imageName);
            $permission->image = $imageName;
        }

        $permission->save();

        return response()->json(['message' => 'Permission created successfully'], 201);
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{
    //index
    public function index(Request $request)
    {
        $permissions = Permission::with('user')
            ->when($request->input('name'), function ($query, $name) {
                $query->whereHas('user', function ($query) use ($name) {
                    $query->where('name', 'like', '%' . $name . '%');
                });
            })->orderBy('id', 'desc')->paginate(10);
        return view('pages.permission.index', compact('permissions'));
    }

    //view
    public function show(Permission $permission)
    {
        return view('pages.permission.show', compact('permission'));
    }

    //edit
    public function edit(Permission $permission)
    {
        return view('pages.permission.edit', compact('permission'));
    }

    //update
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);
        $permission->status = $request->status;
        $permission->save();
        return redirect()->route('permissions.index')->with('success', 'Permission updated successfully');
    }
}

resources/views/pages/permission/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Permission')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('library/bootstrap-social/assets/css/bootstrap.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Edit Permission</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item">Edit Permission</div>
                </div>
            </div>
            <div class="section-body">
                <h2 class="section-title">Edit Permission</h2>
                <p class="section-lead">
                    Perbarui informasi tentang izin karyawan.
                </p>

                <div class="row mt-sm-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <form method="POST" action="{{ route('permissions.update', $permission->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Nama Mahasiswa</label>
                                            <p>{{ $permission->user->name }}</p>
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>NIM Mahasiswa</label>
                                            <p>{{ $permission->user->nim }}</p>
                                        </div>
                                    </div>
                                    <div class="row">

                                        <div class="form-group col-md-6 col-12">
                                            <label>Program Studi</label>
                                            <p>{{ $permission->user->study_program }}</p>
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Fakultas</label>
                                            <p>{{ $permission->user->faculty->name }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Date Permission</label>
                                            <p>{{ $permission->date_permission }}</p>
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Reason</label>
                                            <p>{{ $permission->reason }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Bukti Dukung</label>
                                            <p>
                                                @if ($permission->image)
                                                    <img src="{{ asset('storage/permissions/' . $permission->image) }}"
                                                        alt="Bukti Dukung" style="max-width: 100%; height: auto;">
                                                @else
                                                    Tidak ada bukti pendukung
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Status</label>
                                            <select name="status" class="form-control" style="height: 40px;">
                                                <option value="approved" {{ $permission->status === 'approved' ? 'selected' : '' }}>
                                                    Disetujui
                                                </option>
                                                <option value="rejected" {{ $permission->status === 'rejected' ? 'selected' : '' }}>
                                                    Tidak Disetujui
                                                </option>
                                                <option value="pending" {{ $permission->status === 'pending' ? 'selected' : '' }}>
                                                    Pending
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraries -->
    <script src="{{ asset('library/summernote/dist/summernote-bs4.js') }}"></script>

    <!-- Page Specific JS File -->
@endpush

resources/views/pages/permission/index.blade.php
@extends('layouts.app')

@section('title', 'Permissions')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Permissions</h1>
                {{-- <div class="section-header-button">
                    <a href="{{ route('permissions.create') }}" class="btn btn-primary">Add New</a>
                </div> --}}
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Permissions</a></div>
                    <div class="breadcrumb-item">All Permissions</div>
                </div>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        @include('layouts.alert')
                    </div>
                </div>
                <h2 class="section-title">Permissions</h2>
                <p class="section-lead">
                    You can manage all Permissions, such as editing, deleting and more.
                </p>


                <div class="row mt-4">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>All Permissions</h4>
                            </div>
                            <div class="card-body">

                                <div class="float-right">
                                    <form method="GET" action="{{ route('permissions.index') }}">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Search by name" name="name">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="clearfix mb-3"></div>

                                <div class="table-responsive">
                                    <table class="table-striped table-hover table">
                                        <tr>

                                            <th>Name</th>
                                            <th>Program Studi</th>
                                            <th>Fakultas</th>
                                            <th>Date Permission</th>
                                            <th class="text-center">Status</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                        @foreach ($permissions as $permission)
                                            <tr>
                                                <td>
                                                    <span>{{ $permission->user->name }}</span>
                                                </td>
                                                <td>
                                                    <span class="badge badge-primary">{{ $permission->user->department->name }}</span>
                                                </td>
                                                <td>
                                                    <span class="badge badge-primary">
                                                        {{ $permission->user->faculty->name }}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span class="badge badge-light text-dark">
                                                        <i class="fas fa-calendar-alt"></i> {{ $permission->date_permission }}
                                                    </span>
                                                </td>
                                                <td>
                                                    @if ($permission->status == 'approved')
                                                        <div class="badge badge-success">Approved</div>
                                                    @elseif ($permission->status == 'rejected')
                                                        <div class="badge badge-danger">Not Approved</div>
                                                    @else
                                                        <div class="badge badge-warning">Pending</div>
                                                    @endif
                                                </td>
                                                <td>
                                                    <div class="d-flex justify-content-center">
                                                        <a href='{{ route('permissions.show', $permission->id) }}'
                                                            class="btn btn-sm btn-info btn-icon" title="Show Details">
                                                            <i class="fas fa-circle-info"></i>
                                                        </a>

                                                        <form action="{{ route('permissions.destroy', $permission->id) }}"
                                                            method="POST" class="ml-2">
                                                            <input type="hidden" name="_method" value="DELETE" />
                                                            <input type="hidden" name="_token"
                                                                value="{{ csrf_token() }}" />
                                                            <button class="btn btn-sm btn-danger btn-icon confirm-delete" title="Delete">
                                                                <i class="fas fa-trash"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                                <div class="float-right">
                                    {{ $permissions->withQueryString()->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/selectric/public/jquery.selectric.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/features-posts.js') }}"></script>
@endpush

resources/views/pages/permission/show.blade.php
@extends('layouts.app')

@section('title', 'Permission Detail')

@push('style')
<!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('library/bootstrap-social/assets/css/bootstrap.css') }}">

    <!-- magnific-popup css cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Permission Detail</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item">Permission Detail</div>
                </div>
            </div>
            <div class="section-body">
                <h2 class="section-title">Permission Detail</h2>
                <p class="section-lead">
                    Informasi tentang detail izin mahasiswa.
                </p>
                <div class="row mt-sm-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Nama Mahasiswa</label>
                                        <p>{{ $permission->user->name }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>NIM Mahasiswa</label>
                                        <p>{{ $permission->user->nim }}</p>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Program Studi</label>
                                        <p>{{ $permission->user->department->name }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Fakultas</label>
                                        <p>{{ $permission->user->faculty->name }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Date Permission</label>
                                        <p>{{ $permission->date_permission }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Reason</label>
                                        <p>{{ $permission->reason }}</p>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Bukti Pendukung Izin</label>
                                        <div class="gallery">
                                            <div class="image-container">
                                                @if ($permission->image)
                                                    <a href="{{ asset('storage/permissions/' . $permission->image) }}">
                                                        <img src="{{ asset('storage/permissions/' . $permission->image) }}" alt="Bukti Dukung" class="img-thumbnail mb-3" style="max-width: 200px">
                                                    </a>
                                                @else
                                                    <p class="badge badge-info">Tidak ada bukti pendukung</p>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Status</label>
                                            <p>
                                                @if ($permission->status == 'approved')
                                                    Approved
                                                @elseif ($permission->status == 'rejected')
                                                    Not Approved
                                                @else
                                                    Pending Approval
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <a href="{{ route('permissions.edit', $permission->id) }}" class="btn btn-primary">Edit
                                    Permission For Approve</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Gallery Images Bukti izin -->

    </div>
@endsection

@push('scripts')
    <!-- JS Libraries -->
    <script src="{{ asset('library/summernote/dist/summernote-bs4.js') }}"></script>

    <!-- magnific popup js cdn link  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

    <script>
        $(document).ready(function(){
            $('.gallery').magnificPopup({
                delegate:'a',
                type:'image',
                gallery:{
                    enabled:true
                }
            });
        });
    </script>
@endpush