routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\FacultyController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UniversityController;

Route::get('/', function () {
    return view('pages.auth.auth-login');
});

//Route feature contact
Route::get('/features-contact', [ContactController::class, 'show'])->name('contact');


//Route feature activities
Route::get('/features-activities', [ProfileController::class, 'activities'])->name('activities');

//Route feature tickets
Route::get('/features-tickets', [ProfileController::class, 'tickets'])->name('tickets');

//Route feature settings
Route::get('/features-settings', [SettingController::class, 'settings'])->name('settings');

//Route feature settings detail
Route::get('/features-settings-detail', [SettingController::class, 'settingDetail'])->name('setting-detail');

//Route feature post
Route::get('/features-post', [PostController::class, 'show'])->name('show');

//Route feature post
Route::get('/features-post/create', [PostController::class, 'create'])->name('create');

//Route feature post
Route::post('/features-post/store', [PostController::class, 'store'])->name('store');

Route::group(['middleware' => 'admin'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'show'])->name('home');

    Route::get('/departments', [DepartmentController::class, 'index'])->name('departments.index');

    //Route feature profile
    Route::get('/features-profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile/delete', [ProfileController::class, 'destroy'])->name('profile.delete');

    Route::post('/profile/change-password', [PasswordController::class, 'changePassword'])->name('profile.change-password');

    Route::resource('users', UserController::class);
    Route::resource('faculties', FacultyController::class);
    Route::resource('universites', UniversityController::class);
    Route::resource('attendances', AttendanceController::class);
    Route::resource('permissions', PermissionController::class);
});

app/Models/University.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class University extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'address',
        'phone_number',
        'latitude',
        'longitude',
        'radius_km',
        'time_in',
        'time_out',
    ];
}

app/Http/Controllers/Api/UniversitiesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\University;
use Illuminate\Http\Request;

class UniversitiesController extends Controller
{
    public function index()
    {
        $universite = University::find(1);
        return response(['universities' => $universite], 200);
    }
}

app/Http/Controllers/UniversityController.php
<?php

namespace App\Http\Controllers;

use App\Models\University;
use Illuminate\Http\Request;

class UniversityController extends Controller
{
    //show
    public function show($id)
    {
        $university = University::find(1);
        return view('pages.university.show', compact('university'));
    }

    //edit
    public function edit($id)
    {
        $university = University::find($id);
        return view('pages.university.edit', compact('university'));
    }

    //update
    public function update(Request $request, University $universite)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'address' => 'required',
            'phone_number' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
            'radius_km' => 'required',
            'time_in' => 'required',
            'time_out' => 'required',
        ]);

        $universite->update([
            'name' => $request->name,
            'email' => $request->email,
            'address' => $request->address,
            'phone_number' => $request->phone_number,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'radius_km' => $request->radius_km,
            'time_in' => $request->time_in,
            'time_out' => $request->time_out,
        ]);

        return redirect()->route('universites.show',1)->with('success', 'University updated successfully');
    }
}

resources/views/pages/university/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Profil Universitas')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('library/bootstrap-social/assets/css/bootstrap.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Edit Profil Universitas</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item">Edit Profil Perusahaan</div>
                </div>
            </div>
            <div class="section-body">
                <h2 class="section-title">Edit Profil Universitas</h2>
                <p class="section-lead">
                    Perbarui informasi tentang universitas Anda di halaman ini.
                </p>

                <div class="row mt-sm-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <form method="POST" action="{{ route('universites.update', $university->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Nama Universitas</label>
                                            <input type="text" name="name" class="form-control"
                                                value="{{ $university->name }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Email Universitas</label>
                                            <input type="email" name="email" class="form-control"
                                                value="{{ $university->email }}">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Alamat Universitas</label>
                                            <input type="text" name="address" class="form-control"
                                                value="{{ $university->address }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Telepon Universitas</label>
                                            <input type="tel" name="phone_number" class="form-control" value="{{ $university->phone_number }}">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Deskripsi Universitas</label>
                                            <input type="text" name="description" class="form-control" value="{{ $university->description }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Latitude</label>
                                            <input type="text" name="latitude" class="form-control"
                                                value="{{ $university->latitude }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Longitude</label>
                                            <input type="text" name="longitude" class="form-control"
                                                value="{{ $university->longitude }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Radius KM</label>
                                            <input type="number" step="0.01" name="radius_km" class="form-control"
                                                value="{{ $university->radius_km }}">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-12">
                                            <label>Waktu Masuk</label>
                                            <input type="time" name="time_in" class="form-control"
                                                value="{{ $university->time_in }}">
                                        </div>
                                        <div class="form-group col-md-6 col-12">
                                            <label>Waktu Pulang</label>
                                            <input type="time" name="time_out" class="form-control"
                                                value="{{ $university->time_out }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraries -->
    <script src="{{ asset('library/summernote/dist/summernote-bs4.js') }}"></script>

    <!-- Page Specific JS File -->
@endpush

resources/views/pages/university/show.blade.php
@extends('layouts.app')

@section('title', 'Profile University')

@push('style')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('library/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('library/bootstrap-social/assets/css/bootstrap.css') }}">
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Profile Universitas</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item">Profile Perusahaan</div>
                </div>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        @include('layouts.alert')
                    </div>
                </div>
                <h2 class="section-title">Profil Universitas</h2>
                <p class="section-lead">
                    Informasi tentang universitas Anda.
                </p>

                <div class="row mt-sm-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Nama Universitas</label>
                                        <p>{{ $university->name }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Alamat Universitas</label>
                                        <p>{{ $university->address }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Email Perusahaan</label>
                                        <p>{{ $university->email }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Nomor Telepon</label>
                                        <p>{{ $university->phone_number }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Deskripsi Universitas</label>
                                        <p>{{ $university->description }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Jumlah Fakultas</label>
                                        <p>{{ $university->total_faculty }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Latitude</label>
                                        <p>{{ $university->latitude }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Longitude</label>
                                        <p>{{ $university->longitude }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6 col-12">
                                        <label>Waktu Masuk</label>
                                        <p>{{ $university->time_in }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Waktu Pulang</label>
                                        <p>{{ $university->time_out }}</p>
                                    </div>
                                    <div class="form-group col-md-6 col-12">
                                        <label>Radius KM</label>
                                        <p>{{ $university->radius_km }} KM</p>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <a href="{{ route('universites.edit', $university->id) }}" class="btn btn-primary">Edit Profil
                                    Universitas</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraries -->
    <script src="{{ asset('library/summernote/dist/summernote-bs4.js') }}"></script>

    <!-- Page Specific JS File -->
@endpush